import { db } from "./db";
import { contractors, timesheets, invoices, payRuns, payRunLines, documents, notifications, messages, settings, leaveRequests, payItems } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const existingContractors = await db.select().from(contractors).limit(1);
  if (existingContractors.length > 0) return;

  console.log("Seeding database...");

  const [c1, c2, c3, c4, c5] = await db.insert(contractors).values([
    {
      firstName: "Alex",
      lastName: "Rivera",
      email: "alex.rivera@email.com",
      phone: "0412 345 678",
      jobTitle: "Senior Developer",
      clientName: "Department of Defence",
      status: "ACTIVE",
      clearanceLevel: "NV1",
      clearanceExpiry: "2027-06-15",
      employmentType: "LABOURHIRE",
      payFrequency: "MONTHLY",
      hourlyRate: "125.00",
      contractHoursPA: 2000,
      startDate: "2024-03-01",
      state: "ACT",
      suburb: "Barton",
      accentColour: "#2563eb",
    },
    {
      firstName: "Priya",
      lastName: "Sharma",
      email: "priya.sharma@email.com",
      phone: "0423 456 789",
      jobTitle: "Data Analyst",
      clientName: "Services Australia",
      status: "ACTIVE",
      clearanceLevel: "BASELINE",
      clearanceExpiry: "2028-01-20",
      employmentType: "LABOURHIRE",
      payFrequency: "FORTNIGHTLY",
      hourlyRate: "95.00",
      contractHoursPA: 1800,
      startDate: "2024-07-15",
      state: "ACT",
      suburb: "Tuggeranong",
      accentColour: "#7c3aed",
    },
    {
      firstName: "Marcus",
      lastName: "Chen",
      email: "marcus.chen@email.com",
      phone: "0434 567 890",
      jobTitle: "Cloud Engineer",
      clientName: "ATO",
      status: "ACTIVE",
      clearanceLevel: "NV2",
      clearanceExpiry: "2026-11-30",
      employmentType: "LABOURHIRE",
      payFrequency: "MONTHLY",
      hourlyRate: "145.00",
      contractHoursPA: 2080,
      startDate: "2023-09-01",
      state: "NSW",
      suburb: "Sydney CBD",
      accentColour: "#16a34a",
    },
    {
      firstName: "Sophie",
      lastName: "Williams",
      email: "sophie.williams@email.com",
      phone: "0445 678 901",
      jobTitle: "Project Manager",
      clientName: "Home Affairs",
      status: "PENDING_SETUP",
      clearanceLevel: "NV1",
      employmentType: "LABOURHIRE",
      payFrequency: "MONTHLY",
      hourlyRate: "135.00",
      contractHoursPA: 2000,
      startDate: "2026-04-01",
      state: "ACT",
      suburb: "Campbell",
      accentColour: "#b45309",
    },
    {
      firstName: "James",
      lastName: "O'Brien",
      email: "james.obrien@email.com",
      phone: "0456 789 012",
      jobTitle: "Cyber Security Analyst",
      clientName: "ASIO",
      status: "ACTIVE",
      clearanceLevel: "PV",
      clearanceExpiry: "2027-03-15",
      employmentType: "LABOURHIRE",
      payFrequency: "MONTHLY",
      hourlyRate: "165.00",
      contractHoursPA: 2000,
      startDate: "2024-01-15",
      state: "ACT",
      suburb: "Russell",
      accentColour: "#dc2626",
    },
  ]).returning();

  await db.insert(timesheets).values([
    {
      contractorId: c1.id,
      year: 2026,
      month: 3,
      totalHours: "168.00",
      regularHours: "160.00",
      overtimeHours: "8.00",
      grossValue: "21000.00",
      status: "SUBMITTED",
      fileName: "alex-march-2026.pdf",
      submittedAt: new Date("2026-03-28"),
    },
    {
      contractorId: c2.id,
      year: 2026,
      month: 3,
      totalHours: "152.00",
      regularHours: "152.00",
      overtimeHours: "0.00",
      grossValue: "14440.00",
      status: "APPROVED",
      fileName: "priya-march-2026.pdf",
      submittedAt: new Date("2026-03-25"),
      reviewedAt: new Date("2026-03-26"),
    },
    {
      contractorId: c3.id,
      year: 2026,
      month: 3,
      totalHours: "176.00",
      regularHours: "160.00",
      overtimeHours: "16.00",
      grossValue: "25520.00",
      status: "SUBMITTED",
      fileName: "marcus-march-2026.pdf",
      submittedAt: new Date("2026-03-27"),
    },
    {
      contractorId: c5.id,
      year: 2026,
      month: 3,
      totalHours: "160.00",
      regularHours: "160.00",
      overtimeHours: "0.00",
      grossValue: "26400.00",
      status: "DRAFT",
      fileName: "james-march-2026.pdf",
    },
    {
      contractorId: c1.id,
      year: 2026,
      month: 2,
      totalHours: "160.00",
      regularHours: "160.00",
      overtimeHours: "0.00",
      grossValue: "20000.00",
      status: "APPROVED",
      fileName: "alex-feb-2026.pdf",
      submittedAt: new Date("2026-02-26"),
      reviewedAt: new Date("2026-02-27"),
    },
  ]);

  await db.insert(invoices).values([
    {
      contractorId: c1.id,
      year: 2026,
      month: 2,
      invoiceNumber: "INV-0041",
      amountExclGst: "20000.00",
      gstAmount: "2000.00",
      amountInclGst: "22000.00",
      hours: "160.00",
      hourlyRate: "125.00",
      description: "Alex Rivera - February 2026 - Senior Developer services",
      issueDate: "2026-03-01",
      dueDate: "2026-03-31",
      status: "SENT",
    },
    {
      contractorId: c2.id,
      year: 2026,
      month: 2,
      invoiceNumber: "INV-0042",
      amountExclGst: "14440.00",
      gstAmount: "1444.00",
      amountInclGst: "15884.00",
      hours: "152.00",
      hourlyRate: "95.00",
      description: "Priya Sharma - February 2026 - Data Analyst services",
      issueDate: "2026-03-01",
      dueDate: "2026-03-31",
      status: "PAID",
      paidDate: "2026-03-18",
    },
    {
      contractorId: c3.id,
      year: 2026,
      month: 2,
      invoiceNumber: "INV-0043",
      amountExclGst: "23200.00",
      gstAmount: "2320.00",
      amountInclGst: "25520.00",
      hours: "160.00",
      hourlyRate: "145.00",
      description: "Marcus Chen - February 2026 - Cloud Engineer services",
      issueDate: "2026-03-01",
      dueDate: "2026-03-15",
      status: "OVERDUE",
    },
    {
      contractorId: c5.id,
      year: 2026,
      month: 2,
      invoiceNumber: "INV-0044",
      amountExclGst: "26400.00",
      gstAmount: "2640.00",
      amountInclGst: "29040.00",
      hours: "160.00",
      hourlyRate: "165.00",
      description: "James O'Brien - February 2026 - Cyber Security services",
      issueDate: "2026-03-01",
      dueDate: "2026-03-31",
      status: "AUTHORISED",
    },
  ]);

  const [pr1, pr2] = await db.insert(payRuns).values([
    {
      payRunRef: "PR-2026-02",
      year: 2026,
      month: 2,
      payDate: "2026-02-28",
      periodStart: "2026-02-01",
      periodEnd: "2026-02-28",
      paymentDate: "2026-03-07",
      superRate: "0.1150",
      totalGross: "84040.00",
      totalPayg: "25212.00",
      totalSuper: "9664.60",
      totalNet: "58828.00",
      employeeCount: 4,
      status: "FILED",
    },
    {
      payRunRef: "PR-2026-03",
      year: 2026,
      month: 3,
      payDate: "2026-03-31",
      periodStart: "2026-03-01",
      periodEnd: "2026-03-31",
      paymentDate: "2026-04-07",
      superRate: "0.1150",
      totalGross: "87360.00",
      totalPayg: "26208.00",
      totalSuper: "10046.40",
      totalNet: "61152.00",
      employeeCount: 4,
      status: "DRAFT",
    },
  ]).returning();

  await db.insert(payRunLines).values([
    {
      payRunId: pr1.id,
      contractorId: c1.id,
      hoursWorked: "160.00",
      ratePerHour: "125.00",
      grossEarnings: "20000.00",
      paygWithheld: "5833.00",
      superAmount: "2300.00",
      netPay: "14167.00",
      status: "INCLUDED",
    },
    {
      payRunId: pr1.id,
      contractorId: c2.id,
      hoursWorked: "152.00",
      ratePerHour: "95.00",
      grossEarnings: "14440.00",
      paygWithheld: "3677.00",
      superAmount: "1661.00",
      netPay: "10763.00",
      status: "INCLUDED",
    },
    {
      payRunId: pr1.id,
      contractorId: c3.id,
      hoursWorked: "160.00",
      ratePerHour: "145.00",
      grossEarnings: "23200.00",
      paygWithheld: "7077.00",
      superAmount: "2668.00",
      netPay: "16123.00",
      status: "INCLUDED",
    },
    {
      payRunId: pr1.id,
      contractorId: c5.id,
      hoursWorked: "160.00",
      ratePerHour: "165.00",
      grossEarnings: "26400.00",
      paygWithheld: "8625.00",
      superAmount: "3036.00",
      netPay: "17775.00",
      status: "INCLUDED",
    },
  ]);

  await db.insert(documents).values([
    {
      contractorId: c1.id,
      type: "PAYSLIP",
      name: "Payslip - February 2026",
      fileUrl: `/api/payslips/feb-2026-${c1.id}`,
      fileType: "text/html",
      metadata: JSON.stringify({ year: 2026, month: 2, payRunId: pr1.id }),
    },
    {
      contractorId: c2.id,
      type: "PAYSLIP",
      name: "Payslip - February 2026",
      fileUrl: `/api/payslips/feb-2026-${c2.id}`,
      fileType: "text/html",
      metadata: JSON.stringify({ year: 2026, month: 2, payRunId: pr1.id }),
    },
    {
      contractorId: c1.id,
      type: "CONTRACT",
      name: "Employment Contract - Alex Rivera",
      fileType: "application/pdf",
      metadata: JSON.stringify({ signedDate: "2024-03-01" }),
    },
  ]);

  await db.insert(notifications).values([
    {
      type: "TIMESHEET",
      priority: "HIGH",
      title: "Timesheet returned — Marcus Chen",
      body: "Missing signature on Week 3. Please resubmit.",
      actionLabel: "View timesheet",
      actionRoute: "/timesheets",
      read: false,
      contractorId: c3.id,
    },
    {
      type: "INVOICE",
      priority: "URGENT",
      title: "Invoice overdue — INV-0043",
      body: "Marcus Chen — February 2026 — $25,520 — overdue.",
      actionLabel: "View invoice",
      actionRoute: "/invoices",
      read: false,
      contractorId: c3.id,
    },
    {
      type: "PAYRUN",
      priority: "MEDIUM",
      title: "Pay run due — March 2026",
      body: "3 approved timesheets ready. File before 31 March to meet pay date.",
      actionLabel: "Open pay run",
      actionRoute: "/payroll",
      read: false,
    },
    {
      type: "CLEARANCE",
      priority: "HIGH",
      title: "Clearance expiring — Marcus Chen",
      body: "NV2 clearance expires 30 Nov 2026. Renew 60 days in advance.",
      actionLabel: "View contractor",
      actionRoute: `/contractors/${c3.id}`,
      read: true,
      contractorId: c3.id,
    },
    {
      type: "SYSTEM",
      priority: "LOW",
      title: "System update completed",
      body: "Portal version 2.4 deployed successfully.",
      read: true,
    },
    {
      type: "SUPER",
      priority: "MEDIUM",
      title: "Superannuation due — Q1 2026",
      body: "Quarterly super guarantee payments due by 28 April 2026.",
      actionLabel: "View payroll",
      actionRoute: "/payroll",
      read: false,
    },
  ]);

  await db.insert(messages).values([
    {
      contractorId: c1.id,
      senderRole: "admin",
      subject: "March timesheet reminder",
      body: "Hi Alex, just a reminder that your March timesheet is due by the 28th. Please submit it at your earliest convenience.",
      read: true,
    },
    {
      contractorId: c1.id,
      senderRole: "contractor",
      subject: "Re: March timesheet reminder",
      body: "Thanks Sarah, I've submitted it today. Let me know if anything needs updating.",
      read: true,
    },
    {
      contractorId: c3.id,
      senderRole: "admin",
      subject: "Clearance renewal",
      body: "Hi Marcus, your NV2 clearance is expiring in November. We'll need to start the renewal process soon. I'll send through the forms next week.",
      read: false,
    },
    {
      contractorId: c2.id,
      senderRole: "contractor",
      subject: "Leave request",
      body: "Hi, I'd like to request leave for the week of April 14-18. Could you let me know the process for this?",
      read: false,
    },
  ]);

  await db.insert(settings).values([
    { key: "company_name", value: "Recruitment Portal" },
    { key: "company_abn", value: "12 345 678 901" },
    { key: "company_email", value: "admin@recruitmentportal.com.au" },
    { key: "company_phone", value: "02 1234 5678" },
    { key: "pay_calendar", value: "MONTHLY" },
    { key: "super_rate", value: "11.5" },
    { key: "default_pay_day", value: "28" },
    { key: "portal_enabled", value: "true" },
    { key: "portal_self_service", value: "true" },
  ]);

  await db.insert(leaveRequests).values([
    {
      contractorId: c1.id,
      leaveType: "ANNUAL",
      startDate: "2026-04-14",
      endDate: "2026-04-18",
      totalDays: "5.0",
      reason: "Family holiday planned for school break",
      status: "PENDING",
    },
    {
      contractorId: c2.id,
      leaveType: "SICK",
      startDate: "2026-03-03",
      endDate: "2026-03-04",
      totalDays: "2.0",
      reason: "Unwell — flu symptoms",
      status: "APPROVED",
      reviewedBy: "Sarah Chen",
      reviewNote: "Approved. Get well soon!",
    },
    {
      contractorId: c3.id,
      leaveType: "PERSONAL",
      startDate: "2026-03-21",
      endDate: "2026-03-21",
      totalDays: "1.0",
      reason: "Moving house",
      status: "APPROVED",
      reviewedBy: "Sarah Chen",
    },
    {
      contractorId: c5.id,
      leaveType: "ANNUAL",
      startDate: "2026-05-01",
      endDate: "2026-05-09",
      totalDays: "7.0",
      reason: "Overseas trip — previously discussed",
      status: "PENDING",
    },
  ]);

  await db.insert(payItems).values([
    {
      code: "ORD",
      name: "Ordinary Hours",
      description: "Standard hourly rate",
      itemType: "EARNINGS",
      multiplier: "1.00",
      isTaxable: true,
      isSuperable: true,
      isDefault: true,
      isActive: true,
    },
    {
      code: "OT15",
      name: "Overtime 1.5x",
      description: "Time and a half overtime",
      itemType: "EARNINGS",
      multiplier: "1.50",
      isTaxable: true,
      isSuperable: true,
      isDefault: false,
      isActive: true,
    },
    {
      code: "OT20",
      name: "Overtime 2x",
      description: "Double time overtime",
      itemType: "EARNINGS",
      multiplier: "2.00",
      isTaxable: true,
      isSuperable: true,
      isDefault: false,
      isActive: true,
    },
    {
      code: "PEN",
      name: "Penalty Rates",
      description: "Weekend and public holiday penalty rates",
      itemType: "EARNINGS",
      multiplier: "1.25",
      isTaxable: true,
      isSuperable: true,
      isDefault: false,
      isActive: true,
    },
    {
      code: "AL",
      name: "Annual Leave",
      description: "Paid annual leave",
      itemType: "EARNINGS",
      multiplier: "1.00",
      isTaxable: true,
      isSuperable: true,
      isDefault: true,
      isActive: true,
    },
    {
      code: "SL",
      name: "Sick Leave",
      description: "Paid sick/personal leave",
      itemType: "EARNINGS",
      multiplier: "1.00",
      isTaxable: true,
      isSuperable: true,
      isDefault: true,
      isActive: true,
    },
    {
      code: "ALLOW",
      name: "Travel Allowance",
      description: "Daily travel allowance",
      itemType: "ALLOWANCE",
      rate: "25.00",
      isTaxable: false,
      isSuperable: false,
      isDefault: false,
      isActive: true,
    },
    {
      code: "DED-UNI",
      name: "Union Fees",
      description: "Monthly union membership deduction",
      itemType: "DEDUCTION",
      rate: "45.00",
      isTaxable: false,
      isSuperable: false,
      isDefault: false,
      isActive: false,
    },
  ]);

  console.log("Database seeded successfully!");
}
